package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Adjustments generated by hbm2java
 */
public class Adjustments implements java.io.Serializable {

	private int id;
	private Users users;
	private Warehouses warehouses;
	private Date date;
	private String ref;
	private Double items;
	private String notes;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set adjustmentDetailses = new HashSet(0);

	public Adjustments() {
	}

	public Adjustments(int id, Users users, Warehouses warehouses, Date date, String ref) {
		this.id = id;
		this.users = users;
		this.warehouses = warehouses;
		this.date = date;
		this.ref = ref;
	}

	public Adjustments(int id, Users users, Warehouses warehouses, Date date, String ref, Double items, String notes,
			Date createdAt, Date updatedAt, Date deletedAt, Set adjustmentDetailses) {
		this.id = id;
		this.users = users;
		this.warehouses = warehouses;
		this.date = date;
		this.ref = ref;
		this.items = items;
		this.notes = notes;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.adjustmentDetailses = adjustmentDetailses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public Double getItems() {
		return this.items;
	}

	public void setItems(Double items) {
		this.items = items;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getAdjustmentDetailses() {
		return this.adjustmentDetailses;
	}

	public void setAdjustmentDetailses(Set adjustmentDetailses) {
		this.adjustmentDetailses = adjustmentDetailses;
	}

}
