package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * AdjustmentDetails generated by hbm2java
 */
public class AdjustmentDetails implements java.io.Serializable {

	private int id;
	private Adjustments adjustments;
	private ProductVariants productVariants;
	private Products products;
	private double quantity;
	private String type;
	private Date createdAt;
	private Date updatedAt;

	public AdjustmentDetails() {
	}

	public AdjustmentDetails(int id, Adjustments adjustments, Products products, double quantity, String type) {
		this.id = id;
		this.adjustments = adjustments;
		this.products = products;
		this.quantity = quantity;
		this.type = type;
	}

	public AdjustmentDetails(int id, Adjustments adjustments, ProductVariants productVariants, Products products,
			double quantity, String type, Date createdAt, Date updatedAt) {
		this.id = id;
		this.adjustments = adjustments;
		this.productVariants = productVariants;
		this.products = products;
		this.quantity = quantity;
		this.type = type;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adjustments getAdjustments() {
		return this.adjustments;
	}

	public void setAdjustments(Adjustments adjustments) {
		this.adjustments = adjustments;
	}

	public ProductVariants getProductVariants() {
		return this.productVariants;
	}

	public void setProductVariants(ProductVariants productVariants) {
		this.productVariants = productVariants;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
