package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	private int id;
	private String name;
	private int code;
	private String email;
	private String country;
	private String city;
	private String phone;
	private String adresse;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set saleses = new HashSet(0);
	private Set saleReturnses = new HashSet(0);
	private Set settingses = new HashSet(0);
	private Set quotationses = new HashSet(0);

	public Clients() {
	}

	public Clients(int id, String name, int code, String email, String country, String city, String phone,
			String adresse) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.email = email;
		this.country = country;
		this.city = city;
		this.phone = phone;
		this.adresse = adresse;
	}

	public Clients(int id, String name, int code, String email, String country, String city, String phone,
			String adresse, Date createdAt, Date updatedAt, Date deletedAt, Set saleses, Set saleReturnses,
			Set settingses, Set quotationses) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.email = email;
		this.country = country;
		this.city = city;
		this.phone = phone;
		this.adresse = adresse;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.saleses = saleses;
		this.saleReturnses = saleReturnses;
		this.settingses = settingses;
		this.quotationses = quotationses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set saleses) {
		this.saleses = saleses;
	}

	public Set getSaleReturnses() {
		return this.saleReturnses;
	}

	public void setSaleReturnses(Set saleReturnses) {
		this.saleReturnses = saleReturnses;
	}

	public Set getSettingses() {
		return this.settingses;
	}

	public void setSettingses(Set settingses) {
		this.settingses = settingses;
	}

	public Set getQuotationses() {
		return this.quotationses;
	}

	public void setQuotationses(Set quotationses) {
		this.quotationses = quotationses;
	}

}
