package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Currencies generated by hbm2java
 */
public class Currencies implements java.io.Serializable {

	private int id;
	private String code;
	private String name;
	private String symbol;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set settingses = new HashSet(0);

	public Currencies() {
	}

	public Currencies(int id, String code, String name, String symbol) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.symbol = symbol;
	}

	public Currencies(int id, String code, String name, String symbol, Date createdAt, Date updatedAt, Date deletedAt,
			Set settingses) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.symbol = symbol;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.settingses = settingses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getSettingses() {
		return this.settingses;
	}

	public void setSettingses(Set settingses) {
		this.settingses = settingses;
	}

}
