package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExpenseCategories generated by hbm2java
 */
public class ExpenseCategories implements java.io.Serializable {

	private int id;
	private Users users;
	private String name;
	private String description;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set expenseses = new HashSet(0);

	public ExpenseCategories() {
	}

	public ExpenseCategories(int id, Users users, String name) {
		this.id = id;
		this.users = users;
		this.name = name;
	}

	public ExpenseCategories(int id, Users users, String name, String description, Date createdAt, Date updatedAt,
			Date deletedAt, Set expenseses) {
		this.id = id;
		this.users = users;
		this.name = name;
		this.description = description;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.expenseses = expenseses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getExpenseses() {
		return this.expenseses;
	}

	public void setExpenseses(Set expenseses) {
		this.expenseses = expenseses;
	}

}
