package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * Expenses generated by hbm2java
 */
public class Expenses implements java.io.Serializable {

	private int id;
	private ExpenseCategories expenseCategories;
	private Users users;
	private Warehouses warehouses;
	private Date date;
	private String ref;
	private String details;
	private double amount;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;

	public Expenses() {
	}

	public Expenses(int id, ExpenseCategories expenseCategories, Users users, Warehouses warehouses, Date date,
			String ref, String details, double amount) {
		this.id = id;
		this.expenseCategories = expenseCategories;
		this.users = users;
		this.warehouses = warehouses;
		this.date = date;
		this.ref = ref;
		this.details = details;
		this.amount = amount;
	}

	public Expenses(int id, ExpenseCategories expenseCategories, Users users, Warehouses warehouses, Date date,
			String ref, String details, double amount, Date createdAt, Date updatedAt, Date deletedAt) {
		this.id = id;
		this.expenseCategories = expenseCategories;
		this.users = users;
		this.warehouses = warehouses;
		this.date = date;
		this.ref = ref;
		this.details = details;
		this.amount = amount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ExpenseCategories getExpenseCategories() {
		return this.expenseCategories;
	}

	public void setExpenseCategories(ExpenseCategories expenseCategories) {
		this.expenseCategories = expenseCategories;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

}
