package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

/**
 * Migrations generated by hbm2java
 */
public class Migrations implements java.io.Serializable {

	private int id;
	private String migration;
	private int batch;

	public Migrations() {
	}

	public Migrations(int id, String migration, int batch) {
		this.id = id;
		this.migration = migration;
		this.batch = batch;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMigration() {
		return this.migration;
	}

	public void setMigration(String migration) {
		this.migration = migration;
	}

	public int getBatch() {
		return this.batch;
	}

	public void setBatch(int batch) {
		this.batch = batch;
	}

}
