package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

/**
 * OauthRefreshTokens generated by hbm2java
 */
public class OauthRefreshTokens implements java.io.Serializable {

	private OauthRefreshTokensId id;

	public OauthRefreshTokens() {
	}

	public OauthRefreshTokens(OauthRefreshTokensId id) {
		this.id = id;
	}

	public OauthRefreshTokensId getId() {
		return this.id;
	}

	public void setId(OauthRefreshTokensId id) {
		this.id = id;
	}

}
