package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * OauthPersonalAccessClients generated by hbm2java
 */
public class OauthPersonalAccessClients implements java.io.Serializable {

	private int id;
	private int clientId;
	private Date createdAt;
	private Date updatedAt;

	public OauthPersonalAccessClients() {
	}

	public OauthPersonalAccessClients(int id, int clientId) {
		this.id = id;
		this.clientId = clientId;
	}

	public OauthPersonalAccessClients(int id, int clientId, Date createdAt, Date updatedAt) {
		this.id = id;
		this.clientId = clientId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
