package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * OauthClients generated by hbm2java
 */
public class OauthClients implements java.io.Serializable {

	private int id;
	private Integer userId;
	private String name;
	private String secret;
	private String provider;
	private String redirect;
	private short personalAccessClient;
	private short passwordClient;
	private short revoked;
	private Date createdAt;
	private Date updatedAt;

	public OauthClients() {
	}

	public OauthClients(int id, String name, String redirect, short personalAccessClient, short passwordClient,
			short revoked) {
		this.id = id;
		this.name = name;
		this.redirect = redirect;
		this.personalAccessClient = personalAccessClient;
		this.passwordClient = passwordClient;
		this.revoked = revoked;
	}

	public OauthClients(int id, Integer userId, String name, String secret, String provider, String redirect,
			short personalAccessClient, short passwordClient, short revoked, Date createdAt, Date updatedAt) {
		this.id = id;
		this.userId = userId;
		this.name = name;
		this.secret = secret;
		this.provider = provider;
		this.redirect = redirect;
		this.personalAccessClient = personalAccessClient;
		this.passwordClient = passwordClient;
		this.revoked = revoked;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public String getRedirect() {
		return this.redirect;
	}

	public void setRedirect(String redirect) {
		this.redirect = redirect;
	}

	public short getPersonalAccessClient() {
		return this.personalAccessClient;
	}

	public void setPersonalAccessClient(short personalAccessClient) {
		this.personalAccessClient = personalAccessClient;
	}

	public short getPasswordClient() {
		return this.passwordClient;
	}

	public void setPasswordClient(short passwordClient) {
		this.passwordClient = passwordClient;
	}

	public short getRevoked() {
		return this.revoked;
	}

	public void setRevoked(short revoked) {
		this.revoked = revoked;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
