package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

/**
 * OauthAuthCodes generated by hbm2java
 */
public class OauthAuthCodes implements java.io.Serializable {

	private OauthAuthCodesId id;

	public OauthAuthCodes() {
	}

	public OauthAuthCodes(OauthAuthCodesId id) {
		this.id = id;
	}

	public OauthAuthCodesId getId() {
		return this.id;
	}

	public void setId(OauthAuthCodesId id) {
		this.id = id;
	}

}
