package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

/**
 * OauthAccessTokens generated by hbm2java
 */
public class OauthAccessTokens implements java.io.Serializable {

	private OauthAccessTokensId id;

	public OauthAccessTokens() {
	}

	public OauthAccessTokens(OauthAccessTokensId id) {
		this.id = id;
	}

	public OauthAccessTokensId getId() {
		return this.id;
	}

	public void setId(OauthAccessTokensId id) {
		this.id = id;
	}

}
