package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * PasswordResets generated by hbm2java
 */
public class PasswordResets implements java.io.Serializable {

	private int id;
	private String email;
	private String token;
	private Date createdAt;
	private Date updatedAt;

	public PasswordResets() {
	}

	public PasswordResets(int id, String email, String token) {
		this.id = id;
		this.email = email;
		this.token = token;
	}

	public PasswordResets(int id, String email, String token, Date createdAt, Date updatedAt) {
		this.id = id;
		this.email = email;
		this.token = token;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
