package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * PaymentWithCreditCard generated by hbm2java
 */
public class PaymentWithCreditCard implements java.io.Serializable {

	private int id;
	private int paymentId;
	private int customerId;
	private String customerStripeId;
	private String chargeId;
	private Date createdAt;
	private Date updatedAt;

	public PaymentWithCreditCard() {
	}

	public PaymentWithCreditCard(int id, int paymentId, int customerId, String customerStripeId, String chargeId) {
		this.id = id;
		this.paymentId = paymentId;
		this.customerId = customerId;
		this.customerStripeId = customerStripeId;
		this.chargeId = chargeId;
	}

	public PaymentWithCreditCard(int id, int paymentId, int customerId, String customerStripeId, String chargeId,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.paymentId = paymentId;
		this.customerId = customerId;
		this.customerStripeId = customerStripeId;
		this.chargeId = chargeId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getCustomerStripeId() {
		return this.customerStripeId;
	}

	public void setCustomerStripeId(String customerStripeId) {
		this.customerStripeId = customerStripeId;
	}

	public String getChargeId() {
		return this.chargeId;
	}

	public void setChargeId(String chargeId) {
		this.chargeId = chargeId;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
