package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permissions generated by hbm2java
 */
public class Permissions implements java.io.Serializable {

	private int id;
	private String name;
	private String label;
	private String description;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set permissionRoles = new HashSet(0);

	public Permissions() {
	}

	public Permissions(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Permissions(int id, String name, String label, String description, Date createdAt, Date updatedAt,
			Date deletedAt, Set permissionRoles) {
		this.id = id;
		this.name = name;
		this.label = label;
		this.description = description;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.permissionRoles = permissionRoles;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getPermissionRoles() {
		return this.permissionRoles;
	}

	public void setPermissionRoles(Set permissionRoles) {
		this.permissionRoles = permissionRoles;
	}

}
