package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

/**
 * PermissionRole generated by hbm2java
 */
public class PermissionRole implements java.io.Serializable {

	private int id;
	private Permissions permissions;
	private Roles roles;

	public PermissionRole() {
	}

	public PermissionRole(int id, Permissions permissions, Roles roles) {
		this.id = id;
		this.permissions = permissions;
		this.roles = roles;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Permissions getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
