package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * ProductWarehouse generated by hbm2java
 */
public class ProductWarehouse implements java.io.Serializable {

	private int id;
	private ProductVariants productVariants;
	private Products products;
	private Warehouses warehouses;
	private double qte;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;

	public ProductWarehouse() {
	}

	public ProductWarehouse(int id, Products products, Warehouses warehouses, double qte) {
		this.id = id;
		this.products = products;
		this.warehouses = warehouses;
		this.qte = qte;
	}

	public ProductWarehouse(int id, ProductVariants productVariants, Products products, Warehouses warehouses,
			double qte, Date createdAt, Date updatedAt, Date deletedAt) {
		this.id = id;
		this.productVariants = productVariants;
		this.products = products;
		this.warehouses = warehouses;
		this.qte = qte;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductVariants getProductVariants() {
		return this.productVariants;
	}

	public void setProductVariants(ProductVariants productVariants) {
		this.productVariants = productVariants;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public double getQte() {
		return this.qte;
	}

	public void setQte(double qte) {
		this.qte = qte;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

}
