package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductVariants generated by hbm2java
 */
public class ProductVariants implements java.io.Serializable {

	private int id;
	private Products products;
	private String name;
	private BigDecimal qty;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set purchaseReturnDetailses = new HashSet(0);
	private Set saleReturnDetailses = new HashSet(0);
	private Set adjustmentDetailses = new HashSet(0);
	private Set saleDetailses = new HashSet(0);
	private Set quotationDetailses = new HashSet(0);
	private Set productWarehouses = new HashSet(0);
	private Set purchaseDetailses = new HashSet(0);
	private Set transferDetailses = new HashSet(0);

	public ProductVariants() {
	}

	public ProductVariants(int id) {
		this.id = id;
	}

	public ProductVariants(int id, Products products, String name, BigDecimal qty, Date createdAt, Date updatedAt,
			Date deletedAt, Set purchaseReturnDetailses, Set saleReturnDetailses, Set adjustmentDetailses,
			Set saleDetailses, Set quotationDetailses, Set productWarehouses, Set purchaseDetailses,
			Set transferDetailses) {
		this.id = id;
		this.products = products;
		this.name = name;
		this.qty = qty;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.purchaseReturnDetailses = purchaseReturnDetailses;
		this.saleReturnDetailses = saleReturnDetailses;
		this.adjustmentDetailses = adjustmentDetailses;
		this.saleDetailses = saleDetailses;
		this.quotationDetailses = quotationDetailses;
		this.productWarehouses = productWarehouses;
		this.purchaseDetailses = purchaseDetailses;
		this.transferDetailses = transferDetailses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getPurchaseReturnDetailses() {
		return this.purchaseReturnDetailses;
	}

	public void setPurchaseReturnDetailses(Set purchaseReturnDetailses) {
		this.purchaseReturnDetailses = purchaseReturnDetailses;
	}

	public Set getSaleReturnDetailses() {
		return this.saleReturnDetailses;
	}

	public void setSaleReturnDetailses(Set saleReturnDetailses) {
		this.saleReturnDetailses = saleReturnDetailses;
	}

	public Set getAdjustmentDetailses() {
		return this.adjustmentDetailses;
	}

	public void setAdjustmentDetailses(Set adjustmentDetailses) {
		this.adjustmentDetailses = adjustmentDetailses;
	}

	public Set getSaleDetailses() {
		return this.saleDetailses;
	}

	public void setSaleDetailses(Set saleDetailses) {
		this.saleDetailses = saleDetailses;
	}

	public Set getQuotationDetailses() {
		return this.quotationDetailses;
	}

	public void setQuotationDetailses(Set quotationDetailses) {
		this.quotationDetailses = quotationDetailses;
	}

	public Set getProductWarehouses() {
		return this.productWarehouses;
	}

	public void setProductWarehouses(Set productWarehouses) {
		this.productWarehouses = productWarehouses;
	}

	public Set getPurchaseDetailses() {
		return this.purchaseDetailses;
	}

	public void setPurchaseDetailses(Set purchaseDetailses) {
		this.purchaseDetailses = purchaseDetailses;
	}

	public Set getTransferDetailses() {
		return this.transferDetailses;
	}

	public void setTransferDetailses(Set transferDetailses) {
		this.transferDetailses = transferDetailses;
	}

}
