package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int id;
	private Brands brands;
	private Categories categories;
	private Units unitsByUnitPurchaseId;
	private Units unitsByUnitSaleId;
	private Units unitsByUnitId;
	private String code;
	private String typeBarcode;
	private String name;
	private double cost;
	private double price;
	private Double taxnet;
	private String taxMethod;
	private String image;
	private String note;
	private Double stockAlert;
	private short isVariant;
	private Short isActive;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set saleDetailses = new HashSet(0);
	private Set quotationDetailses = new HashSet(0);
	private Set productWarehouses = new HashSet(0);
	private Set purchaseReturnDetailses = new HashSet(0);
	private Set purchaseDetailses = new HashSet(0);
	private Set productVariantses = new HashSet(0);
	private Set transferDetailses = new HashSet(0);
	private Set saleReturnDetailses = new HashSet(0);
	private Set adjustmentDetailses = new HashSet(0);

	public Products() {
	}

	public Products(int id, Categories categories, String code, String typeBarcode, String name, double cost,
			double price, short isVariant) {
		this.id = id;
		this.categories = categories;
		this.code = code;
		this.typeBarcode = typeBarcode;
		this.name = name;
		this.cost = cost;
		this.price = price;
		this.isVariant = isVariant;
	}

	public Products(int id, Brands brands, Categories categories, Units unitsByUnitPurchaseId, Units unitsByUnitSaleId,
			Units unitsByUnitId, String code, String typeBarcode, String name, double cost, double price, Double taxnet,
			String taxMethod, String image, String note, Double stockAlert, short isVariant, Short isActive,
			Date createdAt, Date updatedAt, Date deletedAt, Set saleDetailses, Set quotationDetailses,
			Set productWarehouses, Set purchaseReturnDetailses, Set purchaseDetailses, Set productVariantses,
			Set transferDetailses, Set saleReturnDetailses, Set adjustmentDetailses) {
		this.id = id;
		this.brands = brands;
		this.categories = categories;
		this.unitsByUnitPurchaseId = unitsByUnitPurchaseId;
		this.unitsByUnitSaleId = unitsByUnitSaleId;
		this.unitsByUnitId = unitsByUnitId;
		this.code = code;
		this.typeBarcode = typeBarcode;
		this.name = name;
		this.cost = cost;
		this.price = price;
		this.taxnet = taxnet;
		this.taxMethod = taxMethod;
		this.image = image;
		this.note = note;
		this.stockAlert = stockAlert;
		this.isVariant = isVariant;
		this.isActive = isActive;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.saleDetailses = saleDetailses;
		this.quotationDetailses = quotationDetailses;
		this.productWarehouses = productWarehouses;
		this.purchaseReturnDetailses = purchaseReturnDetailses;
		this.purchaseDetailses = purchaseDetailses;
		this.productVariantses = productVariantses;
		this.transferDetailses = transferDetailses;
		this.saleReturnDetailses = saleReturnDetailses;
		this.adjustmentDetailses = adjustmentDetailses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public Units getUnitsByUnitPurchaseId() {
		return this.unitsByUnitPurchaseId;
	}

	public void setUnitsByUnitPurchaseId(Units unitsByUnitPurchaseId) {
		this.unitsByUnitPurchaseId = unitsByUnitPurchaseId;
	}

	public Units getUnitsByUnitSaleId() {
		return this.unitsByUnitSaleId;
	}

	public void setUnitsByUnitSaleId(Units unitsByUnitSaleId) {
		this.unitsByUnitSaleId = unitsByUnitSaleId;
	}

	public Units getUnitsByUnitId() {
		return this.unitsByUnitId;
	}

	public void setUnitsByUnitId(Units unitsByUnitId) {
		this.unitsByUnitId = unitsByUnitId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTypeBarcode() {
		return this.typeBarcode;
	}

	public void setTypeBarcode(String typeBarcode) {
		this.typeBarcode = typeBarcode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getCost() {
		return this.cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Double getTaxnet() {
		return this.taxnet;
	}

	public void setTaxnet(Double taxnet) {
		this.taxnet = taxnet;
	}

	public String getTaxMethod() {
		return this.taxMethod;
	}

	public void setTaxMethod(String taxMethod) {
		this.taxMethod = taxMethod;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Double getStockAlert() {
		return this.stockAlert;
	}

	public void setStockAlert(Double stockAlert) {
		this.stockAlert = stockAlert;
	}

	public short getIsVariant() {
		return this.isVariant;
	}

	public void setIsVariant(short isVariant) {
		this.isVariant = isVariant;
	}

	public Short getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Short isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getSaleDetailses() {
		return this.saleDetailses;
	}

	public void setSaleDetailses(Set saleDetailses) {
		this.saleDetailses = saleDetailses;
	}

	public Set getQuotationDetailses() {
		return this.quotationDetailses;
	}

	public void setQuotationDetailses(Set quotationDetailses) {
		this.quotationDetailses = quotationDetailses;
	}

	public Set getProductWarehouses() {
		return this.productWarehouses;
	}

	public void setProductWarehouses(Set productWarehouses) {
		this.productWarehouses = productWarehouses;
	}

	public Set getPurchaseReturnDetailses() {
		return this.purchaseReturnDetailses;
	}

	public void setPurchaseReturnDetailses(Set purchaseReturnDetailses) {
		this.purchaseReturnDetailses = purchaseReturnDetailses;
	}

	public Set getPurchaseDetailses() {
		return this.purchaseDetailses;
	}

	public void setPurchaseDetailses(Set purchaseDetailses) {
		this.purchaseDetailses = purchaseDetailses;
	}

	public Set getProductVariantses() {
		return this.productVariantses;
	}

	public void setProductVariantses(Set productVariantses) {
		this.productVariantses = productVariantses;
	}

	public Set getTransferDetailses() {
		return this.transferDetailses;
	}

	public void setTransferDetailses(Set transferDetailses) {
		this.transferDetailses = transferDetailses;
	}

	public Set getSaleReturnDetailses() {
		return this.saleReturnDetailses;
	}

	public void setSaleReturnDetailses(Set saleReturnDetailses) {
		this.saleReturnDetailses = saleReturnDetailses;
	}

	public Set getAdjustmentDetailses() {
		return this.adjustmentDetailses;
	}

	public void setAdjustmentDetailses(Set adjustmentDetailses) {
		this.adjustmentDetailses = adjustmentDetailses;
	}

}
