package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * RoleUser generated by hbm2java
 */
public class RoleUser implements java.io.Serializable {

	private int id;
	private Roles roles;
	private Users users;
	private Date createdAt;
	private Date updatedAt;

	public RoleUser() {
	}

	public RoleUser(int id, Roles roles, Users users) {
		this.id = id;
		this.roles = roles;
		this.users = users;
	}

	public RoleUser(int id, Roles roles, Users users, Date createdAt, Date updatedAt) {
		this.id = id;
		this.roles = roles;
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
