package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * Servers generated by hbm2java
 */
public class Servers implements java.io.Serializable {

	private int id;
	private String host;
	private int port;
	private String username;
	private String password;
	private String encryption;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;

	public Servers() {
	}

	public Servers(int id, String host, int port, String username, String password, String encryption) {
		this.id = id;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
		this.encryption = encryption;
	}

	public Servers(int id, String host, int port, String username, String password, String encryption, Date createdAt,
			Date updatedAt, Date deletedAt) {
		this.id = id;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
		this.encryption = encryption;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEncryption() {
		return this.encryption;
	}

	public void setEncryption(String encryption) {
		this.encryption = encryption;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

}
