package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Units generated by hbm2java
 */
public class Units implements java.io.Serializable {

	private int id;
	private Units units;
	private String name;
	private String shortname;
	private String operator;
	private Double operatorValue;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set productsesForUnitPurchaseId = new HashSet(0);
	private Set purchaseDetailses = new HashSet(0);
	private Set quotationDetailses = new HashSet(0);
	private Set productsesForUnitSaleId = new HashSet(0);
	private Set saleDetailses = new HashSet(0);
	private Set purchaseReturnDetailses = new HashSet(0);
	private Set productsesForUnitId = new HashSet(0);
	private Set saleReturnDetailses = new HashSet(0);
	private Set transferDetailses = new HashSet(0);
	private Set unitses = new HashSet(0);

	public Units() {
	}

	public Units(int id, String name, String shortname) {
		this.id = id;
		this.name = name;
		this.shortname = shortname;
	}

	public Units(int id, Units units, String name, String shortname, String operator, Double operatorValue,
			Date createdAt, Date updatedAt, Date deletedAt, Set productsesForUnitPurchaseId, Set purchaseDetailses,
			Set quotationDetailses, Set productsesForUnitSaleId, Set saleDetailses, Set purchaseReturnDetailses,
			Set productsesForUnitId, Set saleReturnDetailses, Set transferDetailses, Set unitses) {
		this.id = id;
		this.units = units;
		this.name = name;
		this.shortname = shortname;
		this.operator = operator;
		this.operatorValue = operatorValue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.productsesForUnitPurchaseId = productsesForUnitPurchaseId;
		this.purchaseDetailses = purchaseDetailses;
		this.quotationDetailses = quotationDetailses;
		this.productsesForUnitSaleId = productsesForUnitSaleId;
		this.saleDetailses = saleDetailses;
		this.purchaseReturnDetailses = purchaseReturnDetailses;
		this.productsesForUnitId = productsesForUnitId;
		this.saleReturnDetailses = saleReturnDetailses;
		this.transferDetailses = transferDetailses;
		this.unitses = unitses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Units getUnits() {
		return this.units;
	}

	public void setUnits(Units units) {
		this.units = units;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Double getOperatorValue() {
		return this.operatorValue;
	}

	public void setOperatorValue(Double operatorValue) {
		this.operatorValue = operatorValue;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getProductsesForUnitPurchaseId() {
		return this.productsesForUnitPurchaseId;
	}

	public void setProductsesForUnitPurchaseId(Set productsesForUnitPurchaseId) {
		this.productsesForUnitPurchaseId = productsesForUnitPurchaseId;
	}

	public Set getPurchaseDetailses() {
		return this.purchaseDetailses;
	}

	public void setPurchaseDetailses(Set purchaseDetailses) {
		this.purchaseDetailses = purchaseDetailses;
	}

	public Set getQuotationDetailses() {
		return this.quotationDetailses;
	}

	public void setQuotationDetailses(Set quotationDetailses) {
		this.quotationDetailses = quotationDetailses;
	}

	public Set getProductsesForUnitSaleId() {
		return this.productsesForUnitSaleId;
	}

	public void setProductsesForUnitSaleId(Set productsesForUnitSaleId) {
		this.productsesForUnitSaleId = productsesForUnitSaleId;
	}

	public Set getSaleDetailses() {
		return this.saleDetailses;
	}

	public void setSaleDetailses(Set saleDetailses) {
		this.saleDetailses = saleDetailses;
	}

	public Set getPurchaseReturnDetailses() {
		return this.purchaseReturnDetailses;
	}

	public void setPurchaseReturnDetailses(Set purchaseReturnDetailses) {
		this.purchaseReturnDetailses = purchaseReturnDetailses;
	}

	public Set getProductsesForUnitId() {
		return this.productsesForUnitId;
	}

	public void setProductsesForUnitId(Set productsesForUnitId) {
		this.productsesForUnitId = productsesForUnitId;
	}

	public Set getSaleReturnDetailses() {
		return this.saleReturnDetailses;
	}

	public void setSaleReturnDetailses(Set saleReturnDetailses) {
		this.saleReturnDetailses = saleReturnDetailses;
	}

	public Set getTransferDetailses() {
		return this.transferDetailses;
	}

	public void setTransferDetailses(Set transferDetailses) {
		this.transferDetailses = transferDetailses;
	}

	public Set getUnitses() {
		return this.unitses;
	}

	public void setUnitses(Set unitses) {
		this.unitses = unitses;
	}

}
