package com.example.pojo;
// Generated 23 avr. 2022, 13:06:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Warehouses generated by hbm2java
 */
public class Warehouses implements java.io.Serializable {

	private int id;
	private String name;
	private String city;
	private String mobile;
	private String zip;
	private String email;
	private String country;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set productWarehouses = new HashSet(0);
	private Set quotationses = new HashSet(0);
	private Set saleReturnses = new HashSet(0);
	private Set transfersesForFromWarehouseId = new HashSet(0);
	private Set transfersesForToWarehouseId = new HashSet(0);
	private Set purchaseses = new HashSet(0);
	private Set saleses = new HashSet(0);
	private Set settingses = new HashSet(0);
	private Set expenseses = new HashSet(0);
	private Set purchaseReturnses = new HashSet(0);
	private Set adjustmentses = new HashSet(0);

	public Warehouses() {
	}

	public Warehouses(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Warehouses(int id, String name, String city, String mobile, String zip, String email, String country,
			Date createdAt, Date updatedAt, Date deletedAt, Set productWarehouses, Set quotationses, Set saleReturnses,
			Set transfersesForFromWarehouseId, Set transfersesForToWarehouseId, Set purchaseses, Set saleses,
			Set settingses, Set expenseses, Set purchaseReturnses, Set adjustmentses) {
		this.id = id;
		this.name = name;
		this.city = city;
		this.mobile = mobile;
		this.zip = zip;
		this.email = email;
		this.country = country;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.productWarehouses = productWarehouses;
		this.quotationses = quotationses;
		this.saleReturnses = saleReturnses;
		this.transfersesForFromWarehouseId = transfersesForFromWarehouseId;
		this.transfersesForToWarehouseId = transfersesForToWarehouseId;
		this.purchaseses = purchaseses;
		this.saleses = saleses;
		this.settingses = settingses;
		this.expenseses = expenseses;
		this.purchaseReturnses = purchaseReturnses;
		this.adjustmentses = adjustmentses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getProductWarehouses() {
		return this.productWarehouses;
	}

	public void setProductWarehouses(Set productWarehouses) {
		this.productWarehouses = productWarehouses;
	}

	public Set getQuotationses() {
		return this.quotationses;
	}

	public void setQuotationses(Set quotationses) {
		this.quotationses = quotationses;
	}

	public Set getSaleReturnses() {
		return this.saleReturnses;
	}

	public void setSaleReturnses(Set saleReturnses) {
		this.saleReturnses = saleReturnses;
	}

	public Set getTransfersesForFromWarehouseId() {
		return this.transfersesForFromWarehouseId;
	}

	public void setTransfersesForFromWarehouseId(Set transfersesForFromWarehouseId) {
		this.transfersesForFromWarehouseId = transfersesForFromWarehouseId;
	}

	public Set getTransfersesForToWarehouseId() {
		return this.transfersesForToWarehouseId;
	}

	public void setTransfersesForToWarehouseId(Set transfersesForToWarehouseId) {
		this.transfersesForToWarehouseId = transfersesForToWarehouseId;
	}

	public Set getPurchaseses() {
		return this.purchaseses;
	}

	public void setPurchaseses(Set purchaseses) {
		this.purchaseses = purchaseses;
	}

	public Set getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set saleses) {
		this.saleses = saleses;
	}

	public Set getSettingses() {
		return this.settingses;
	}

	public void setSettingses(Set settingses) {
		this.settingses = settingses;
	}

	public Set getExpenseses() {
		return this.expenseses;
	}

	public void setExpenseses(Set expenseses) {
		this.expenseses = expenseses;
	}

	public Set getPurchaseReturnses() {
		return this.purchaseReturnses;
	}

	public void setPurchaseReturnses(Set purchaseReturnses) {
		this.purchaseReturnses = purchaseReturnses;
	}

	public Set getAdjustmentses() {
		return this.adjustmentses;
	}

	public void setAdjustmentses(Set adjustmentses) {
		this.adjustmentses = adjustmentses;
	}

}
