package com.example.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Migrations generated by hbm2java
 */
@Entity
@Table(name = "migrations", schema = "public")
public class Migrations implements java.io.Serializable {

	private int id;
	private String migration;
	private int batch;

	public Migrations() {
	}

	public Migrations(int id, String migration, int batch) {
		this.id = id;
		this.migration = migration;
		this.batch = batch;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "migration", nullable = false, length = 191)
	public String getMigration() {
		return this.migration;
	}

	public void setMigration(String migration) {
		this.migration = migration;
	}

	@Column(name = "batch", nullable = false)
	public int getBatch() {
		return this.batch;
	}

	public void setBatch(int batch) {
		this.batch = batch;
	}

}
