package com.example.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OauthPersonalAccessClients generated by hbm2java
 */
@Entity
@Table(name = "oauth_personal_access_clients", schema = "public")
public class OauthPersonalAccessClients implements java.io.Serializable {

	private int id;
	private int clientId;
	private Date createdAt;
	private Date updatedAt;

	public OauthPersonalAccessClients() {
	}

	public OauthPersonalAccessClients(int id, int clientId) {
		this.id = id;
		this.clientId = clientId;
	}

	public OauthPersonalAccessClients(int id, int clientId, Date createdAt, Date updatedAt) {
		this.id = id;
		this.clientId = clientId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "client_id", nullable = false)
	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
