package com.example.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OauthRefreshTokensId generated by hbm2java
 */
@Embeddable
public class OauthRefreshTokensId implements java.io.Serializable {

	private String id;
	private String accessTokenId;
	private short revoked;
	private Date expiresAt;

	public OauthRefreshTokensId() {
	}

	public OauthRefreshTokensId(String id, String accessTokenId, short revoked) {
		this.id = id;
		this.accessTokenId = accessTokenId;
		this.revoked = revoked;
	}

	public OauthRefreshTokensId(String id, String accessTokenId, short revoked, Date expiresAt) {
		this.id = id;
		this.accessTokenId = accessTokenId;
		this.revoked = revoked;
		this.expiresAt = expiresAt;
	}

	@Column(name = "id", nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "access_token_id", nullable = false, length = 100)
	public String getAccessTokenId() {
		return this.accessTokenId;
	}

	public void setAccessTokenId(String accessTokenId) {
		this.accessTokenId = accessTokenId;
	}

	@Column(name = "revoked", nullable = false)
	public short getRevoked() {
		return this.revoked;
	}

	public void setRevoked(short revoked) {
		this.revoked = revoked;
	}

	@Column(name = "expires_at", length = 13)
	public Date getExpiresAt() {
		return this.expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OauthRefreshTokensId))
			return false;
		OauthRefreshTokensId castOther = (OauthRefreshTokensId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getAccessTokenId() == castOther.getAccessTokenId())
						|| (this.getAccessTokenId() != null && castOther.getAccessTokenId() != null
								&& this.getAccessTokenId().equals(castOther.getAccessTokenId())))
				&& (this.getRevoked() == castOther.getRevoked())
				&& ((this.getExpiresAt() == castOther.getExpiresAt()) || (this.getExpiresAt() != null
						&& castOther.getExpiresAt() != null && this.getExpiresAt().equals(castOther.getExpiresAt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getAccessTokenId() == null ? 0 : this.getAccessTokenId().hashCode());
		result = 37 * result + this.getRevoked();
		result = 37 * result + (getExpiresAt() == null ? 0 : this.getExpiresAt().hashCode());
		return result;
	}

}
