package com.example.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OauthAuthCodes generated by hbm2java
 */
@Entity
@Table(name = "oauth_auth_codes", schema = "public")
public class OauthAuthCodes implements java.io.Serializable {

	private OauthAuthCodesId id;

	public OauthAuthCodes() {
	}

	public OauthAuthCodes(OauthAuthCodesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, length = 100)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "clientId", column = @Column(name = "client_id", nullable = false)),
			@AttributeOverride(name = "scopes", column = @Column(name = "scopes")),
			@AttributeOverride(name = "revoked", column = @Column(name = "revoked", nullable = false)),
			@AttributeOverride(name = "expiresAt", column = @Column(name = "expires_at", length = 13)) })
	public OauthAuthCodesId getId() {
		return this.id;
	}

	public void setId(OauthAuthCodesId id) {
		this.id = id;
	}

}
